'use client'

import { Suspense, useCallback, useEffect, useRef, useState, useTransition } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { BarChart3, Clock, FileDown, FileSpreadsheet, GitCompareArrows, LayoutGrid, LayoutList, Map, Sun, TreePalm, UtensilsCrossed, Waves, Wrench, X } from 'lucide-react'
import { Viewer3D } from '@/components/viewer/viewer-3d'
import { ViewerControls } from '@/components/viewer/viewer-controls'
import { OptionsSidebar } from '@/components/design/options-sidebar'
import { GeneratorControls } from '@/components/design/generator-controls'
import { MetricsPanel } from '@/components/design/metrics-panel'
import { ScoringPanel } from '@/components/design/scoring-panel'
import { AmenityPanel } from '@/components/design/amenity-panel'
import { ComparisonPanel } from '@/components/design/comparison-panel'
import { VersionPanel } from '@/components/design/version-panel'
import { FloorPlan } from '@/components/design/floor-plan'
import { OptionsTable } from '@/components/design/options-table'
import { ViewAnalysis } from '@/components/design/view-analysis'
import { FnbDesigner } from '@/components/design/fnb-designer'
import { BohDashboard } from '@/components/design/boh-dashboard'
import { PoolDeckDesigner } from '@/components/design/pool-deck-designer'
import { SitePlanner } from '@/components/design/site-planner'
import dynamic from 'next/dynamic'

const InteractivePlanner = dynamic(
  () => import('@/components/design/interactive-planner').then(m => ({ default: m.InteractivePlanner })),
  { ssr: false }
)
import { generateAll } from '@/engine/generator'
import { useDesign } from '@/context/design-context'
import { exportToExcel } from '@/lib/export-excel'
import { ExportDxfButton } from '@/components/design/export-dxf-button'
import { ExportPptxButton } from '@/components/design/export-pptx-button'
import { canEdit, canExport, canGenerate } from '@/lib/auth'
import { useUser } from '@/lib/use-user'
import { logAudit } from '@/store/audit-store'
import type { DesignOption } from '@/engine/types'

const MODULE_ROUTES = ['/design', '/planning', '/finance', '/dataroom', '/invest'] as const

function GeneratingOverlay() {
  return (
    <div className="absolute inset-0 z-20 flex items-center justify-center bg-slate-950/60 backdrop-blur-sm">
      <div className="text-center">
        <div className="mx-auto mb-3 h-8 w-8 animate-spin rounded-full border-2 border-sky-400 border-t-transparent" />
        <p className="text-sm font-medium text-sky-400">Generating design options...</p>
        <p className="mt-1 text-xs text-slate-500">Evaluating 2,880 combinations</p>
      </div>
    </div>
  )
}

export default function DesignPage() {
  return (
    <Suspense fallback={<div className="flex h-full items-center justify-center bg-slate-950"><div className="h-8 w-8 animate-spin rounded-full border-2 border-sky-400 border-t-transparent" /></div>}>
      <DesignPageInner />
    </Suspense>
  )
}

function DesignPageInner() {
  const { options, selectedOption, setOptions, selectOption } = useDesign()
  const [isPending, startTransition] = useTransition()
  const hasAutoGenerated = useRef(false)
  const router = useRouter()
  const searchParams = useSearchParams()
  const user = useUser()
  const isAdmin = canEdit(user)
  const allowExport = canExport(user)
  const allowGenerate = canGenerate(user)

  // Viewer control state
  const [activePreset, setActivePreset] = useState('3D')
  const [activeBasemap, setActiveBasemap] = useState('OSM Standard')
  const [showBoundaries, setShowBoundaries] = useState(true)
  const [showAmenities, setShowAmenities] = useState(true)
  const [explodedView, setExplodedView] = useState(false)

  // Walkthrough / cinematic / time-of-day state
  const [walkthroughMode, setWalkthroughMode] = useState(false)
  const [cinematicMode, setCinematicMode] = useState(false)
  const [timeOfDay, setTimeOfDay] = useState('midday')

  // Comparison state
  const [compareMode, setCompareMode] = useState(false)
  const [compareOption, setCompareOption] = useState<DesignOption | null>(null)

  // Version history state
  const [showVersions, setShowVersions] = useState(false)

  // Table view state
  const [showTable, setShowTable] = useState(false)

  // Panel visibility state (hidden by default, toggled via action bar)
  const [showScoring, setShowScoring] = useState(false)
  const [showAmenityPanel, setShowAmenityPanel] = useState(false)

  // Open table view if URL param says so
  useEffect(() => {
    if (searchParams.get('view') === 'table') {
      setShowTable(true)
    }
  }, [searchParams])

  // Floor plan & view analysis overlays
  const [showFloorPlan, setShowFloorPlan] = useState(false)
  const [showViewAnalysis, setShowViewAnalysis] = useState(false)
  const [showFnb, setShowFnb] = useState(false)
  const [showBoh, setShowBoh] = useState(false)
  const [showPoolDeck, setShowPoolDeck] = useState(false)
  const [showSitePlan, setShowSitePlan] = useState(false)
  const [showInteractivePlanner, setShowInteractivePlanner] = useState(false)
  const [floorIndex, setFloorIndex] = useState(0)

  const handleGenerate = useCallback(() => {
    startTransition(() => {
      const generated = generateAll(40)
      setOptions(generated)
      if (generated.length > 0) selectOption(generated[0].id)
      // Reset compare state on new generation
      setCompareMode(false)
      setCompareOption(null)
      logAudit({
        userId: user?.name ?? 'unknown',
        userName: user?.name ?? 'Unknown',
        action: 'option_generated',
        target: `Generated ${generated.length} design options`,
        metadata: { count: String(generated.length) },
      })
    })
  }, [setOptions, selectOption, user])

  const handleExportReport = useCallback(() => {
    if (!selectedOption) return
    localStorage.setItem('yotel-selected-option', JSON.stringify(selectedOption))
    window.open('/report', '_blank')
    logAudit({
      userId: user?.name ?? 'unknown',
      userName: user?.name ?? 'Unknown',
      action: 'report_generated',
      target: selectedOption.curatedName ?? `Option ${selectedOption.id.slice(0, 8)}`,
      metadata: { format: 'PDF', form: selectedOption.form },
    })
  }, [selectedOption, user])

  const handleExportExcel = useCallback(() => {
    if (!selectedOption) return
    exportToExcel(selectedOption)
    logAudit({
      userId: user?.name ?? 'unknown',
      userName: user?.name ?? 'Unknown',
      action: 'design_exported',
      target: selectedOption.curatedName ?? `Option ${selectedOption.id.slice(0, 8)}`,
      metadata: { format: 'Excel', form: selectedOption.form },
    })
  }, [selectedOption, user])

  const handleLoadVersion = useCallback(
    (option: DesignOption) => {
      // Inject the loaded option into the current options list (if not already present)
      // and select it
      const exists = options.some((o) => o.id === option.id)
      if (!exists) {
        setOptions([option, ...options])
      }
      selectOption(option.id)
    },
    [options, setOptions, selectOption],
  )

  const handleToggleCompareMode = useCallback(() => {
    setCompareMode((prev) => {
      if (prev) {
        // Turning off -- clear compare option
        setCompareOption(null)
      } else if (selectedOption) {
        logAudit({
          userId: user?.name ?? 'unknown',
          userName: user?.name ?? 'Unknown',
          action: 'comparison_made',
          target: `Entered compare mode from ${selectedOption.curatedName ?? `Option ${selectedOption.id.slice(0, 8)}`}`,
          metadata: { primaryOption: selectedOption.id },
        })
      }
      return !prev
    })
  }, [selectedOption, user])

  // Handle option selection -- in compare mode, second click sets compare target
  const handleOptionSelect = useCallback(
    (id: string) => {
      if (compareMode && selectedOption && id !== selectedOption.id) {
        // In compare mode, clicking a different option sets it as compare target
        const target = options.find((o) => o.id === id)
        if (target) setCompareOption(target)
      } else {
        // Normal selection
        selectOption(id)
        // Clear compare target if we change the primary selection
        setCompareOption(null)
      }
    },
    [compareMode, selectedOption, options, selectOption],
  )

  // Auto-generate on first mount if no options exist
  useEffect(() => {
    if (options.length === 0 && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true
      handleGenerate()
    }
  }, [options.length, handleGenerate])

  // Keyboard shortcuts
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      // Ignore if user is typing in an input or textarea
      const tag = (e.target as HTMLElement)?.tagName
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return

      // 1-5: Switch modules
      const digit = parseInt(e.key, 10)
      if (digit >= 1 && digit <= 5) {
        router.push(MODULE_ROUTES[digit - 1])
        return
      }

      // G: Generate (admin only)
      if (e.key === 'g' || e.key === 'G') {
        if (!isPending && allowGenerate) handleGenerate()
        return
      }

      // C: Toggle compare mode
      if (e.key === 'c' || e.key === 'C') {
        handleToggleCompareMode()
        return
      }

      // Escape: Close overlays, then deselect or exit compare mode
      if (e.key === 'Escape') {
        if (showTable) {
          setShowTable(false)
          return
        }
        if (showFloorPlan) {
          setShowFloorPlan(false)
          return
        }
        if (showViewAnalysis) {
          setShowViewAnalysis(false)
          return
        }
        if (showScoring) {
          setShowScoring(false)
          return
        }
        if (showAmenityPanel) {
          setShowAmenityPanel(false)
          return
        }
        if (compareMode) {
          setCompareMode(false)
          setCompareOption(null)
        } else {
          selectOption(null)
        }
        return
      }

      // Arrow keys: Navigate options
      if ((e.key === 'ArrowUp' || e.key === 'ArrowDown') && options.length > 0) {
        e.preventDefault()
        const currentIndex = selectedOption
          ? options.findIndex((o) => o.id === selectedOption.id)
          : -1

        let nextIndex: number
        if (e.key === 'ArrowDown') {
          nextIndex = currentIndex < options.length - 1 ? currentIndex + 1 : 0
        } else {
          nextIndex = currentIndex > 0 ? currentIndex - 1 : options.length - 1
        }
        selectOption(options[nextIndex].id)
        // Clear compare target when navigating with arrows
        setCompareOption(null)
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [router, isPending, handleGenerate, selectOption, options, selectedOption, compareMode, handleToggleCompareMode, showFloorPlan, showViewAnalysis, showTable, showScoring, showAmenityPanel])

  return (
    <div className="flex h-full flex-col md:flex-row">
      {/* Viewer banner for guests */}
      {user && !isAdmin && (
        <div className="flex items-center justify-center gap-2 bg-amber-500/10 border-b border-amber-500/20 px-4 py-1.5 text-xs text-amber-400 flex-shrink-0">
          <span>Viewing as {user.name} — contact admin for edit access</span>
        </div>
      )}
      {/* Main viewport + panels wrapper -- scrollable on mobile */}
      <div className="flex flex-1 flex-col min-h-0 overflow-y-auto md:overflow-visible">
        {/* 3D viewport area */}
        <div className="relative flex-shrink-0 h-[50vh] md:h-full md:flex-1">
        {/* z-5: 3D viewer fills the viewport */}
        <Viewer3D
          selectedOption={selectedOption}
          className="h-full w-full"
          activePreset={activePreset}
          activeBasemap={activeBasemap}
          showBoundaries={showBoundaries}
          showAmenities={showAmenities}
          explodedView={explodedView}
          walkthroughMode={walkthroughMode}
          cinematicMode={cinematicMode}
          timeOfDay={timeOfDay as 'morning' | 'midday' | 'sunset' | 'night'}
          onWalkthroughExit={() => setWalkthroughMode(false)}
          onCinematicEnd={() => setCinematicMode(false)}
        />

        {/* z-10: Floating panels (collapsed state) / z-15: expanded */}
        {/* Top-left: Metrics panel (collapsible, collapsed by default) */}
        <div className="hidden md:block">
          <MetricsPanel option={selectedOption} />
        </div>

        {/* Top-right: Viewer controls (collapsed by default) */}
        <ViewerControls
          activePreset={activePreset}
          activeBasemap={activeBasemap}
          showBoundaries={showBoundaries}
          showAmenities={showAmenities}
          explodedView={explodedView}
          onCameraChange={setActivePreset}
          onBasemapChange={setActiveBasemap}
          onToggleBoundaries={() => setShowBoundaries((v) => !v)}
          onToggleAmenities={() => setShowAmenities((v) => !v)}
          onToggleExploded={() => setExplodedView((v) => !v)}
          onWalkthrough={() => {
            setWalkthroughMode((v) => !v)
            if (!walkthroughMode) setCinematicMode(false)
          }}
          onCinematic={() => {
            setCinematicMode((v) => !v)
            if (!cinematicMode) setWalkthroughMode(false)
          }}
          isWalking={walkthroughMode}
          isCinematic={cinematicMode}
          timeOfDay={timeOfDay}
          onTimeOfDayChange={setTimeOfDay}
        />

        {/* Loading overlay */}
        {isPending && <GeneratingOverlay />}

        {/* z-15: Scoring panel (hidden by default, toggled via action bar) */}
        <ScoringPanel
          option={selectedOption}
          isOpen={showScoring}
          onClose={() => setShowScoring(false)}
        />

        {/* z-15: Amenity panel (hidden by default, toggled via action bar) */}
        <AmenityPanel
          amenities={selectedOption?.amenities}
          isOpen={showAmenityPanel}
          onClose={() => setShowAmenityPanel(false)}
        />

        {/* Bottom-left: Generator (compact, always visible) */}
        <GeneratorControls onGenerate={handleGenerate} isGenerating={isPending} />

        {/* z-50: Floor Plan overlay -- replaces 3D viewport */}
        {showFloorPlan && (
          <div className="absolute inset-0 z-50 flex flex-col bg-slate-950 transition-all duration-150 ease-out">
            <div className="flex items-center justify-between border-b border-slate-800 px-4 py-2">
              <h2 className="text-sm font-semibold text-slate-200">
                Floor Plan &mdash; {selectedOption?.form ?? ''} Form
              </h2>
              <button
                onClick={() => setShowFloorPlan(false)}
                className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-slate-200"
              >
                <X size={16} />
              </button>
            </div>
            <div className="flex-1 overflow-hidden">
              <FloorPlan
                option={selectedOption}
                floorIndex={floorIndex}
                onFloorChange={setFloorIndex}
              />
            </div>
          </div>
        )}

        {/* z-50: View Analysis floating panel */}
        {showViewAnalysis && (
          <div className="absolute bottom-0 right-0 top-0 z-50 w-full md:w-[380px] border-l border-slate-800 bg-slate-950 shadow-2xl transition-all duration-150 ease-out">
            <div className="flex items-center justify-between border-b border-slate-800 px-4 py-2">
              <h2 className="text-sm font-semibold text-slate-200">
                View &amp; Sun Analysis
              </h2>
              <button
                onClick={() => setShowViewAnalysis(false)}
                className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-slate-200"
              >
                <X size={16} />
              </button>
            </div>
            <div className="h-[calc(100%-40px)] overflow-hidden">
              <ViewAnalysis option={selectedOption} />
            </div>
          </div>
        )}

        {/* z-50: F&B Designer overlay */}
        <FnbDesigner isOpen={showFnb} onClose={() => setShowFnb(false)} />

        {/* z-50: BOH Dashboard overlay */}
        <BohDashboard isOpen={showBoh} onClose={() => setShowBoh(false)} />

        {/* z-50: Pool Deck Designer overlay */}
        <PoolDeckDesigner isOpen={showPoolDeck} onClose={() => setShowPoolDeck(false)} />

        {/* z-50: Site Planner overlay */}
        <SitePlanner isOpen={showSitePlan} onClose={() => setShowSitePlan(false)} selectedOption={selectedOption} />
        <InteractivePlanner isOpen={showInteractivePlanner} onClose={() => setShowInteractivePlanner(false)} selectedOption={selectedOption} />

        {/* z-50: Options Table overlay */}
        <OptionsTable
          options={options}
          selectedId={selectedOption?.id ?? null}
          onSelect={(id) => {
            selectOption(id)
            setShowTable(false)
          }}
          isOpen={showTable}
          onClose={() => setShowTable(false)}
        />

        {/* z-30: Action buttons -- scrollable row at bottom */}
        <div className="absolute bottom-2 right-2 left-2 md:bottom-4 md:right-4 md:left-4 z-30 flex items-center gap-1.5 md:gap-2 overflow-x-auto pb-1 scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-transparent [&::-webkit-scrollbar]:h-0 [&::-webkit-scrollbar]:w-0 [-ms-overflow-style:none] [scrollbar-width:none]">
          {/* Table View button */}
          {options.length > 0 && (
            <button
              onClick={() => setShowTable(true)}
              title="Table View"
              className="flex items-center gap-1.5 md:gap-2 rounded-lg bg-[#0f172a] px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium text-white shadow-lg transition-colors hover:bg-[#1e293b] flex-shrink-0"
            >
              <LayoutList size={14} />
              <span className="hidden sm:inline">Table View</span>
            </button>
          )}

          {/* Scoring panel toggle */}
          {selectedOption && (
            <button
              onClick={() => setShowScoring((v) => !v)}
              title="Score Breakdown"
              className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
                showScoring
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <BarChart3 size={14} />
              <span className="hidden sm:inline">Scoring</span>
            </button>
          )}

          {/* Amenity panel toggle */}
          {selectedOption && (
            <button
              onClick={() => setShowAmenityPanel((v) => !v)}
              title="Amenity Programme"
              className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
                showAmenityPanel
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <TreePalm size={14} />
              <span className="hidden sm:inline">Amenities</span>
            </button>
          )}

          {/* F&B Design button */}
          {selectedOption && (
            <button
              onClick={() => setShowFnb((v) => !v)}
              title="F&B Venue Design"
              className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
                showFnb
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <UtensilsCrossed size={14} />
              <span className="hidden sm:inline">F&amp;B</span>
            </button>
          )}

          {/* BOH Ops button */}
          {selectedOption && (
            <button
              onClick={() => setShowBoh((v) => !v)}
              title="Back of House Operations"
              className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
                showBoh
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <Wrench size={14} />
              <span className="hidden sm:inline">BOH</span>
            </button>
          )}

          {/* Pool Deck button */}
          {selectedOption && (
            <button
              onClick={() => setShowPoolDeck((v) => !v)}
              title="Pool Deck Design"
              className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
                showPoolDeck
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <Waves size={14} />
              <span className="hidden sm:inline">Pool</span>
            </button>
          )}

          {/* Site Plan button */}
          <button
            onClick={() => setShowSitePlan((v) => !v)}
            title="Interactive Site Plan"
            className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
              showSitePlan
                ? 'bg-sky-600 text-white hover:bg-sky-700'
                : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
            }`}
          >
            <Map size={14} />
            <span className="hidden sm:inline">Site Plan</span>
          </button>

          {/* Interactive Planner button -- admin only */}
          {isAdmin && (
            <button
              onClick={() => setShowInteractivePlanner((v) => !v)}
              title="Drag & Drop Site Planner"
              className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
                showInteractivePlanner
                  ? 'bg-emerald-600 text-white hover:bg-emerald-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <LayoutGrid size={14} />
              <span className="hidden sm:inline">Design Studio</span>
            </button>
          )}

          {/* Floor Plan button */}
          {selectedOption && (
            <button
              onClick={() => {
                setShowFloorPlan((v) => !v)
                if (showViewAnalysis) setShowViewAnalysis(false)
              }}
              title="Floor Plans"
              className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
                showFloorPlan
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <LayoutGrid size={14} />
              <span className="hidden sm:inline">Floor Plan</span>
            </button>
          )}

          {/* View Analysis button */}
          {selectedOption && (
            <button
              onClick={() => {
                setShowViewAnalysis((v) => !v)
                if (showFloorPlan) setShowFloorPlan(false)
              }}
              title="View &amp; Sun Analysis"
              className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
                showViewAnalysis
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <Sun size={14} />
              <span className="hidden sm:inline">Views</span>
            </button>
          )}

          {/* Version history button -- admin only */}
          {selectedOption && isAdmin && (
            <button
              onClick={() => setShowVersions(true)}
              title="Version History"
              className="flex items-center gap-1.5 md:gap-2 rounded-lg bg-[#0f172a] px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium text-white shadow-lg transition-colors hover:bg-[#1e293b] flex-shrink-0"
            >
              <Clock size={14} />
              <span className="hidden sm:inline">History</span>
            </button>
          )}

          {/* Compare button */}
          {selectedOption && (
            <button
              onClick={handleToggleCompareMode}
              title={compareMode ? 'Exit compare mode (C)' : 'Compare options (C)'}
              className={`flex items-center gap-1.5 md:gap-2 rounded-lg px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium shadow-lg transition-colors flex-shrink-0 ${
                compareMode
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <GitCompareArrows size={14} />
              <span className="hidden sm:inline">{compareMode ? 'Exit Compare' : 'Compare'}</span>
            </button>
          )}

          {/* DXF CAD Export button -- admin only */}
          {selectedOption && allowExport && (
            <ExportDxfButton option={selectedOption} />
          )}

          {/* Download Excel button -- admin only */}
          {selectedOption && allowExport && (
            <button
              onClick={handleExportExcel}
              title="Download Excel (TSV)"
              className="flex items-center gap-1.5 md:gap-2 rounded-lg bg-[#0f172a] px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium text-white shadow-lg transition-colors hover:bg-[#1e293b] flex-shrink-0"
            >
              <FileSpreadsheet size={14} />
              <span className="hidden sm:inline">Excel</span>
            </button>
          )}

          {/* PPTX Investor Deck button -- admin only */}
          {selectedOption && allowExport && (
            <ExportPptxButton option={selectedOption} />
          )}

          {/* Export Report button -- admin only */}
          {selectedOption && allowExport && (
            <button
              onClick={handleExportReport}
              title="Export Feasibility Report (PDF)"
              className="flex items-center gap-1.5 md:gap-2 rounded-lg bg-[#0f172a] px-2 md:px-3 py-1.5 md:py-2 text-[10px] md:text-xs font-medium text-white shadow-lg transition-colors hover:bg-[#1e293b] flex-shrink-0"
            >
              <FileDown size={14} />
              <span className="hidden sm:inline">Report</span>
            </button>
          )}

          {/* Right spacer so last button isn't flush with edge when scrolling */}
          <div className="flex-shrink-0 w-1" aria-hidden="true" />
        </div>

        {/* z-50: Comparison panel */}
        {compareMode && selectedOption && compareOption && (
          <ComparisonPanel
            optionA={selectedOption}
            optionB={compareOption}
            onClose={handleToggleCompareMode}
          />
        )}

        {/* z-50: Version history panel */}
        <VersionPanel
          isOpen={showVersions}
          onClose={() => setShowVersions(false)}
          onLoad={handleLoadVersion}
          currentOption={selectedOption}
        />
        </div>{/* end viewport div */}

        {/* Mobile stacked panels -- visible below viewport on small screens */}
        <div className="flex flex-col gap-2 p-2 md:hidden">
          <MetricsPanel option={selectedOption} />
          {showScoring && (
            <ScoringPanel option={selectedOption} isOpen={showScoring} onClose={() => setShowScoring(false)} />
          )}
          {showAmenityPanel && (
            <AmenityPanel amenities={selectedOption?.amenities} isOpen={showAmenityPanel} onClose={() => setShowAmenityPanel(false)} />
          )}
        </div>
      </div>{/* end scrollable wrapper */}

      {/* z-20: Right sidebar */}
      <OptionsSidebar
        options={options}
        selectedId={selectedOption?.id ?? null}
        onSelect={handleOptionSelect}
        compareMode={compareMode}
        compareTargetId={compareOption?.id ?? null}
      />
    </div>
  )
}
