'use client'

import { useCallback, useEffect, useRef, useState, useTransition } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Clock, FileDown, FileSpreadsheet, GitCompareArrows, LayoutGrid, LayoutList, Sun, UtensilsCrossed, Waves, Wrench, X } from 'lucide-react'
import { Viewer3D } from '@/components/viewer/viewer-3d'
import { ViewerControls } from '@/components/viewer/viewer-controls'
import { OptionsSidebar } from '@/components/design/options-sidebar'
import { GeneratorControls } from '@/components/design/generator-controls'
import { MetricsPanel } from '@/components/design/metrics-panel'
import { ScoringPanel } from '@/components/design/scoring-panel'
import { AmenityPanel } from '@/components/design/amenity-panel'
import { ComparisonPanel } from '@/components/design/comparison-panel'
import { VersionPanel } from '@/components/design/version-panel'
import { FloorPlan } from '@/components/design/floor-plan'
import { OptionsTable } from '@/components/design/options-table'
import { ViewAnalysis } from '@/components/design/view-analysis'
import { FnbDesigner } from '@/components/design/fnb-designer'
import { BohDashboard } from '@/components/design/boh-dashboard'
import { PoolDeckDesigner } from '@/components/design/pool-deck-designer'
import { generateAll } from '@/engine/generator'
import { useDesign } from '@/context/design-context'
import { exportToExcel } from '@/lib/export-excel'
import type { DesignOption } from '@/engine/types'

const MODULE_ROUTES = ['/design', '/planning', '/finance', '/dataroom', '/invest'] as const

function GeneratingOverlay() {
  return (
    <div className="absolute inset-0 z-20 flex items-center justify-center bg-slate-950/60 backdrop-blur-sm">
      <div className="text-center">
        <div className="mx-auto mb-3 h-8 w-8 animate-spin rounded-full border-2 border-sky-400 border-t-transparent" />
        <p className="text-sm font-medium text-sky-400">Generating design options...</p>
        <p className="mt-1 text-xs text-slate-500">Evaluating 2,880 combinations</p>
      </div>
    </div>
  )
}

export default function DesignPage() {
  const { options, selectedOption, setOptions, selectOption } = useDesign()
  const [isPending, startTransition] = useTransition()
  const hasAutoGenerated = useRef(false)
  const router = useRouter()
  const searchParams = useSearchParams()

  // Viewer control state
  const [activePreset, setActivePreset] = useState('3D')
  const [activeBasemap, setActiveBasemap] = useState('Google')
  const [showBoundaries, setShowBoundaries] = useState(true)
  const [showAmenities, setShowAmenities] = useState(true)
  const [explodedView, setExplodedView] = useState(false)

  // Walkthrough / cinematic / time-of-day state
  const [walkthroughMode, setWalkthroughMode] = useState(false)
  const [cinematicMode, setCinematicMode] = useState(false)
  const [timeOfDay, setTimeOfDay] = useState('midday')

  // Comparison state
  const [compareMode, setCompareMode] = useState(false)
  const [compareOption, setCompareOption] = useState<DesignOption | null>(null)

  // Version history state
  const [showVersions, setShowVersions] = useState(false)

  // Table view state
  const [showTable, setShowTable] = useState(false)

  // Open table view if URL param says so
  useEffect(() => {
    if (searchParams.get('view') === 'table') {
      setShowTable(true)
    }
  }, [searchParams])

  // Floor plan & view analysis overlays
  const [showFloorPlan, setShowFloorPlan] = useState(false)
  const [showViewAnalysis, setShowViewAnalysis] = useState(false)
  const [showFnb, setShowFnb] = useState(false)
  const [showBoh, setShowBoh] = useState(false)
  const [showPoolDeck, setShowPoolDeck] = useState(false)
  const [floorIndex, setFloorIndex] = useState(0)

  const handleGenerate = useCallback(() => {
    startTransition(() => {
      const generated = generateAll(40)
      setOptions(generated)
      if (generated.length > 0) selectOption(generated[0].id)
      // Reset compare state on new generation
      setCompareMode(false)
      setCompareOption(null)
    })
  }, [setOptions, selectOption])

  const handleExportReport = useCallback(() => {
    if (!selectedOption) return
    localStorage.setItem('yotel-selected-option', JSON.stringify(selectedOption))
    window.open('/report', '_blank')
  }, [selectedOption])

  const handleExportExcel = useCallback(() => {
    if (!selectedOption) return
    exportToExcel(selectedOption)
  }, [selectedOption])

  const handleLoadVersion = useCallback(
    (option: DesignOption) => {
      // Inject the loaded option into the current options list (if not already present)
      // and select it
      const exists = options.some((o) => o.id === option.id)
      if (!exists) {
        setOptions([option, ...options])
      }
      selectOption(option.id)
    },
    [options, setOptions, selectOption],
  )

  const handleToggleCompareMode = useCallback(() => {
    setCompareMode((prev) => {
      if (prev) {
        // Turning off — clear compare option
        setCompareOption(null)
      }
      return !prev
    })
  }, [])

  // Handle option selection — in compare mode, second click sets compare target
  const handleOptionSelect = useCallback(
    (id: string) => {
      if (compareMode && selectedOption && id !== selectedOption.id) {
        // In compare mode, clicking a different option sets it as compare target
        const target = options.find((o) => o.id === id)
        if (target) setCompareOption(target)
      } else {
        // Normal selection
        selectOption(id)
        // Clear compare target if we change the primary selection
        setCompareOption(null)
      }
    },
    [compareMode, selectedOption, options, selectOption],
  )

  // Auto-generate on first mount if no options exist
  useEffect(() => {
    if (options.length === 0 && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true
      handleGenerate()
    }
  }, [options.length, handleGenerate])

  // Keyboard shortcuts
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      // Ignore if user is typing in an input or textarea
      const tag = (e.target as HTMLElement)?.tagName
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return

      // 1-5: Switch modules
      const digit = parseInt(e.key, 10)
      if (digit >= 1 && digit <= 5) {
        router.push(MODULE_ROUTES[digit - 1])
        return
      }

      // G: Generate
      if (e.key === 'g' || e.key === 'G') {
        if (!isPending) handleGenerate()
        return
      }

      // C: Toggle compare mode
      if (e.key === 'c' || e.key === 'C') {
        handleToggleCompareMode()
        return
      }

      // Escape: Close overlays, then deselect or exit compare mode
      if (e.key === 'Escape') {
        if (showTable) {
          setShowTable(false)
          return
        }
        if (showFloorPlan) {
          setShowFloorPlan(false)
          return
        }
        if (showViewAnalysis) {
          setShowViewAnalysis(false)
          return
        }
        if (compareMode) {
          setCompareMode(false)
          setCompareOption(null)
        } else {
          selectOption(null)
        }
        return
      }

      // Arrow keys: Navigate options
      if ((e.key === 'ArrowUp' || e.key === 'ArrowDown') && options.length > 0) {
        e.preventDefault()
        const currentIndex = selectedOption
          ? options.findIndex((o) => o.id === selectedOption.id)
          : -1

        let nextIndex: number
        if (e.key === 'ArrowDown') {
          nextIndex = currentIndex < options.length - 1 ? currentIndex + 1 : 0
        } else {
          nextIndex = currentIndex > 0 ? currentIndex - 1 : options.length - 1
        }
        selectOption(options[nextIndex].id)
        // Clear compare target when navigating with arrows
        setCompareOption(null)
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [router, isPending, handleGenerate, selectOption, options, selectedOption, compareMode, handleToggleCompareMode, showFloorPlan, showViewAnalysis, showTable])

  return (
    <div className="flex h-full">
      {/* Main viewport */}
      <div className="relative flex-1">
        <Viewer3D
          selectedOption={selectedOption}
          className="h-full w-full"
          activePreset={activePreset}
          activeBasemap={activeBasemap}
          showBoundaries={showBoundaries}
          showAmenities={showAmenities}
          explodedView={explodedView}
          walkthroughMode={walkthroughMode}
          cinematicMode={cinematicMode}
          timeOfDay={timeOfDay as 'morning' | 'midday' | 'sunset' | 'night'}
          onWalkthroughExit={() => setWalkthroughMode(false)}
          onCinematicEnd={() => setCinematicMode(false)}
        />

        {/* Viewer controls overlay */}
        <ViewerControls
          activePreset={activePreset}
          activeBasemap={activeBasemap}
          showBoundaries={showBoundaries}
          showAmenities={showAmenities}
          explodedView={explodedView}
          onCameraChange={setActivePreset}
          onBasemapChange={setActiveBasemap}
          onToggleBoundaries={() => setShowBoundaries((v) => !v)}
          onToggleAmenities={() => setShowAmenities((v) => !v)}
          onToggleExploded={() => setExplodedView((v) => !v)}
          onWalkthrough={() => {
            setWalkthroughMode((v) => !v)
            if (!walkthroughMode) setCinematicMode(false)
          }}
          onCinematic={() => {
            setCinematicMode((v) => !v)
            if (!cinematicMode) setWalkthroughMode(false)
          }}
          isWalking={walkthroughMode}
          isCinematic={cinematicMode}
          timeOfDay={timeOfDay}
          onTimeOfDayChange={setTimeOfDay}
        />

        {/* Loading overlay */}
        {isPending && <GeneratingOverlay />}

        {/* Floating overlays */}
        <MetricsPanel option={selectedOption} />
        <ScoringPanel option={selectedOption} />
        <GeneratorControls onGenerate={handleGenerate} isGenerating={isPending} />
        <AmenityPanel amenities={selectedOption?.amenities} />

        {/* Floor Plan overlay — replaces 3D viewport */}
        {showFloorPlan && (
          <div className="absolute inset-0 z-30 flex flex-col bg-slate-950">
            <div className="flex items-center justify-between border-b border-slate-800 px-4 py-2">
              <h2 className="text-sm font-semibold text-slate-200">
                Floor Plan &mdash; {selectedOption?.form ?? ''} Form
              </h2>
              <button
                onClick={() => setShowFloorPlan(false)}
                className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-slate-200"
              >
                <X size={16} />
              </button>
            </div>
            <div className="flex-1 overflow-hidden">
              <FloorPlan
                option={selectedOption}
                floorIndex={floorIndex}
                onFloorChange={setFloorIndex}
              />
            </div>
          </div>
        )}

        {/* View Analysis floating panel */}
        {showViewAnalysis && (
          <div className="absolute bottom-0 right-0 top-0 z-30 w-[380px] border-l border-slate-800 bg-slate-950 shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-800 px-4 py-2">
              <h2 className="text-sm font-semibold text-slate-200">
                View &amp; Sun Analysis
              </h2>
              <button
                onClick={() => setShowViewAnalysis(false)}
                className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-slate-200"
              >
                <X size={16} />
              </button>
            </div>
            <div className="h-[calc(100%-40px)] overflow-hidden">
              <ViewAnalysis option={selectedOption} />
            </div>
          </div>
        )}

        {/* F&B Designer overlay */}
        <FnbDesigner isOpen={showFnb} onClose={() => setShowFnb(false)} />

        {/* BOH Dashboard overlay */}
        <BohDashboard isOpen={showBoh} onClose={() => setShowBoh(false)} />

        {/* Pool Deck Designer overlay */}
        <PoolDeckDesigner isOpen={showPoolDeck} onClose={() => setShowPoolDeck(false)} />

        {/* Options Table overlay */}
        <OptionsTable
          options={options}
          selectedId={selectedOption?.id ?? null}
          onSelect={(id) => {
            selectOption(id)
            setShowTable(false)
          }}
          isOpen={showTable}
          onClose={() => setShowTable(false)}
        />

        {/* Action buttons */}
        <div className="absolute bottom-4 right-4 z-20 flex items-center gap-2">
          {/* Table View button */}
          {options.length > 0 && (
            <button
              onClick={() => setShowTable(true)}
              title="Table View"
              className="flex items-center gap-2 rounded-lg bg-[#0f172a] px-3 py-2 text-xs font-medium text-white shadow-lg transition-colors hover:bg-[#1e293b]"
            >
              <LayoutList size={14} />
              Table View
            </button>
          )}

          {/* F&B Design button */}
          {selectedOption && (
            <button
              onClick={() => setShowFnb((v) => !v)}
              title="F&B Venue Design"
              className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-medium shadow-lg transition-colors ${
                showFnb
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <UtensilsCrossed size={14} />
              F&amp;B Design
            </button>
          )}

          {/* BOH Ops button */}
          {selectedOption && (
            <button
              onClick={() => setShowBoh((v) => !v)}
              title="Back of House Operations"
              className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-medium shadow-lg transition-colors ${
                showBoh
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <Wrench size={14} />
              BOH Ops
            </button>
          )}

          {/* Pool Deck button */}
          {selectedOption && (
            <button
              onClick={() => setShowPoolDeck((v) => !v)}
              title="Pool Deck Design"
              className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-medium shadow-lg transition-colors ${
                showPoolDeck
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <Waves size={14} />
              Pool Deck
            </button>
          )}

          {/* Floor Plan button */}
          {selectedOption && (
            <button
              onClick={() => {
                setShowFloorPlan((v) => !v)
                if (showViewAnalysis) setShowViewAnalysis(false)
              }}
              title="Floor Plans"
              className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-medium shadow-lg transition-colors ${
                showFloorPlan
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <LayoutGrid size={14} />
              Floor Plan
            </button>
          )}

          {/* View Analysis button */}
          {selectedOption && (
            <button
              onClick={() => {
                setShowViewAnalysis((v) => !v)
                if (showFloorPlan) setShowFloorPlan(false)
              }}
              title="View &amp; Sun Analysis"
              className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-medium shadow-lg transition-colors ${
                showViewAnalysis
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <Sun size={14} />
              Views
            </button>
          )}

          {/* Version history button */}
          {selectedOption && (
            <button
              onClick={() => setShowVersions(true)}
              title="Version History"
              className="flex items-center gap-2 rounded-lg bg-[#0f172a] px-3 py-2 text-xs font-medium text-white shadow-lg transition-colors hover:bg-[#1e293b]"
            >
              <Clock size={14} />
              History
            </button>
          )}

          {/* Compare button */}
          {selectedOption && (
            <button
              onClick={handleToggleCompareMode}
              title={compareMode ? 'Exit compare mode (C)' : 'Compare options (C)'}
              className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-medium shadow-lg transition-colors ${
                compareMode
                  ? 'bg-sky-600 text-white hover:bg-sky-700'
                  : 'bg-[#0f172a] text-white hover:bg-[#1e293b]'
              }`}
            >
              <GitCompareArrows size={14} />
              {compareMode ? 'Exit Compare' : 'Compare'}
            </button>
          )}

          {/* Download Excel button */}
          {selectedOption && (
            <button
              onClick={handleExportExcel}
              title="Download Excel (TSV)"
              className="flex items-center gap-2 rounded-lg bg-[#0f172a] px-3 py-2 text-xs font-medium text-white shadow-lg transition-colors hover:bg-[#1e293b]"
            >
              <FileSpreadsheet size={14} />
              Download Excel
            </button>
          )}

          {/* Export Report button */}
          {selectedOption && (
            <button
              onClick={handleExportReport}
              title="Export Feasibility Report (PDF)"
              className="flex items-center gap-2 rounded-lg bg-[#0f172a] px-3 py-2 text-xs font-medium text-white shadow-lg transition-colors hover:bg-[#1e293b]"
            >
              <FileDown size={14} />
              Export Report
            </button>
          )}
        </div>

        {/* Comparison panel */}
        {compareMode && selectedOption && compareOption && (
          <ComparisonPanel
            optionA={selectedOption}
            optionB={compareOption}
            onClose={handleToggleCompareMode}
          />
        )}

        {/* Version history panel */}
        <VersionPanel
          isOpen={showVersions}
          onClose={() => setShowVersions(false)}
          onLoad={handleLoadVersion}
          currentOption={selectedOption}
        />
      </div>

      {/* Right sidebar */}
      <OptionsSidebar
        options={options}
        selectedId={selectedOption?.id ?? null}
        onSelect={handleOptionSelect}
        compareMode={compareMode}
        compareTargetId={compareOption?.id ?? null}
      />
    </div>
  )
}
