'use client'

import { useCallback, useEffect, useRef, useTransition } from 'react'
import { Viewer3D } from '@/components/viewer/viewer-3d'
import { OptionsSidebar } from '@/components/design/options-sidebar'
import { GeneratorControls } from '@/components/design/generator-controls'
import { MetricsPanel } from '@/components/design/metrics-panel'
import { ScoringPanel } from '@/components/design/scoring-panel'
import { AmenityPanel } from '@/components/design/amenity-panel'
import { generateAll } from '@/engine/generator'
import { useDesign } from '@/context/design-context'

export default function DesignPage() {
  const { options, selectedOption, setOptions, selectOption } = useDesign()
  const [isPending, startTransition] = useTransition()
  const hasAutoGenerated = useRef(false)

  const handleGenerate = useCallback(() => {
    startTransition(() => {
      const generated = generateAll(40)
      setOptions(generated)
      if (generated.length > 0) selectOption(generated[0].id)
    })
  }, [setOptions, selectOption])

  // Auto-generate on first mount if no options exist
  useEffect(() => {
    if (options.length === 0 && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true
      handleGenerate()
    }
  }, [options.length, handleGenerate])

  return (
    <div className="flex h-full">
      {/* Main viewport */}
      <div className="relative flex-1">
        <Viewer3D selectedOption={selectedOption} className="h-full w-full" />

        {/* Floating overlays */}
        <MetricsPanel option={selectedOption} />
        <ScoringPanel option={selectedOption} />
        <GeneratorControls onGenerate={handleGenerate} isGenerating={isPending} />
        <AmenityPanel amenities={selectedOption?.amenities} />
      </div>

      {/* Right sidebar */}
      <OptionsSidebar
        options={options}
        selectedId={selectedOption?.id ?? null}
        onSelect={selectOption}
      />
    </div>
  )
}
